package org.blue.taskflow.domain.entity.task;

// Generated 2009-12-17 11:09:01 by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

import org.blue.taskflow.domain.entity.IdEntity;
import org.blue.taskflow.domain.entity.organization.Employee;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "TASK_TASK")
public class Task extends IdEntity implements java.io.Serializable {

	private String name;
	private String content;
	private Employee createEmployee;
    private Employee belongEmployee;
	private Date startTime;
	private Date endTime;
	private Date createTime;
	private String typeCode;
	private String state;
    private Set<TaskStateLog> taskStateLogs = new HashSet<TaskStateLog>(0);

	public Task() {
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CONTENT", length = 2000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATE_EMPLOYEE_ID")
	public Employee getCreateEmployee() {
		return this.createEmployee;
	}

	public void setCreateEmployee(Employee createEmployee) {
		this.createEmployee = createEmployee;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BELONG_EMPLOYEE_ID")
	public Employee getBelongEmployee() {
		return this.belongEmployee;
	}

	public void setBelongEmployee(Employee belongEmployee) {
		this.belongEmployee = belongEmployee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_TIME")
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_TIME")
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME")
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "TYPE_CODE", length = 2)
	public String getTypeCode() {
		return typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "STATE",length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "task", orphanRemoval = true)
    public Set<TaskStateLog> getTaskStateLogs() {
        return taskStateLogs;
    }

    public void setTaskStateLogs(Set<TaskStateLog> taskStateLogs) {
        this.taskStateLogs = taskStateLogs;
    }
}
